export const localVideos = {
    "media/De xuat cho ban/Bàn Tay Diệt Quỷ/Ban_Tay_Diet_Quy.mp4": require("../../assets/media/De xuat cho ban/Bàn Tay Diệt Quỷ/Ban_Tay_Diet_Quy.mp4"),
    "media/De xuat cho ban/Cộng Sự Bất Đắc Dĩ/Cong_Su_Bat_Dac_Di.mp4": require("../../assets/media/De xuat cho ban/Cộng Sự Bất Đắc Dĩ/Cong_Su_Bat_Dac_Di.mp4"),
    "media/De xuat cho ban/Giải Mã Mê Cung/Giai_Ma_Me_Cung.mp4": require("../../assets/media/De xuat cho ban/Giải Mã Mê Cung/Giai_Ma_Me_Cung.mp4"),
    "media/De xuat cho ban/Joker/Joker.mp4": require("../../assets/media/De xuat cho ban/Joker/Joker.mp4"),
    "media/De xuat cho ban/Mật Vụ Kingsman/Mat_Vu_Kingsman.mp4": require("../../assets/media/De xuat cho ban/Mật Vụ Kingsman/Mat_Vu_Kingsman.mp4"),
    "media/De xuat cho ban/Năm Mươi Sắc Thái/Nam_Muoi_Sac_Thai.mp4": require("../../assets/media/De xuat cho ban/Năm Mươi Sắc Thái/Nam_Muoi_Sac_Thai.mp4"),
    "media/De xuat cho ban/Phù Thủy Tối Thượng/Phu_Thuy_Toi_Thuong.mp4": require("../../assets/media/De xuat cho ban/Phù Thủy Tối Thượng/Phu_Thuy_Toi_Thuong.mp4"),
    "media/De xuat cho ban/Sinh Vật Huyền Bí Và Nơi Tìm Ra Chúng/Sinh_Vat_Huyen_Bi_Va_Noi_Tim_Ra_Chung.mp4": require("../../assets/media/De xuat cho ban/Sinh Vật Huyền Bí Và Nơi Tìm Ra Chúng/Sinh_Vat_Huyen_Bi_Va_Noi_Tim_Ra_Chung.mp4"),
    "media/De xuat cho ban/Sói Già Phố Wall/Soi_Gia_Pho_Wall.mp4": require("../../assets/media/De xuat cho ban/Sói Già Phố Wall/Soi_Gia_Pho_Wall.mp4"),
    "media/De xuat cho ban/Thị Trấn Wonka/Thi_Tran_Wonka.mp4": require("../../assets/media/De xuat cho ban/Thị Trấn Wonka/Thi_Tran_Wonka.mp4"),
    "media/Hai huoc/404 Chạy Ngay Đi/404_Chay_Ngay_Di.mp4": require("../../assets/media/Hai huoc/404 Chạy Ngay Đi/404_Chay_Ngay_Di.mp4"),
    "media/Hai huoc/Anh Không Đau/Anh_Khong_Dau.mp4": require("../../assets/media/Hai huoc/Anh Không Đau/Anh_Khong_Dau.mp4"),
    "media/Hai huoc/Dưa Hấu Lấp Lánh/Dua_Hau_Lap_Lanh.mp4": require("../../assets/media/Hai huoc/Dưa Hấu Lấp Lánh/Dua_Hau_Lap_Lanh.mp4"),
    "media/Hai huoc/Gia Đình Hiện Đại/Gia_Dinh_Hien_Dai.mp4": require("../../assets/media/Hai huoc/Gia Đình Hiện Đại/Gia_Dinh_Hien_Dai.mp4"),
    "media/Hai huoc/Gia Đình Là Số Một 2 Chung Một Mái Nhà/Gia_Dinh_La_So_Mot_2_Chung_Mot_Mai_Nha.mp4": require("../../assets/media/Hai huoc/Gia Đình Là Số Một 2 Chung Một Mái Nhà/Gia_Dinh_La_So_Mot_2_Chung_Mot_Mai_Nha.mp4"),
    "media/Hai huoc/Hành Trình Của Moana 2/Hanh_Trinh_Cua_Moana_2.mp4": require("../../assets/media/Hai huoc/Hành Trình Của Moana 2/Hanh_Trinh_Cua_Moana_2.mp4"),
    "media/Hai huoc/Linh Mục Nhiệt Huyết/Linh_Muc_Nhiet_Huyet.mp4": require("../../assets/media/Hai huoc/Linh Mục Nhiệt Huyết/Linh_Muc_Nhiet_Huyet.mp4"),
    "media/Hai huoc/SAKAMOTO DAYS Sát Thủ Về Vườn/SAKAMOTO_DAYS_Sat_Thu_Ve_Vuon.mp4": require("../../assets/media/Hai huoc/SAKAMOTO DAYS Sát Thủ Về Vườn/SAKAMOTO_DAYS_Sat_Thu_Ve_Vuon.mp4"),
    "media/Hai huoc/Sát Thủ Vô Cùng Cực Hài/Sat_Thu_Vo_Cung_Cuc_Hai.mp4": require("../../assets/media/Hai huoc/Sát Thủ Vô Cùng Cực Hài/Sat_Thu_Vo_Cung_Cuc_Hai.mp4"),
    "media/Hanh dong/Baybylon/Baybylon.mp4": require("../../assets/media/Hanh dong/Baybylon/Baybylon.mp4"),
    "media/Hanh dong/Chuyện Ngày Xưa ở Hollywood/Chuyen_Ngay_Xua_o_Hollywood.mp4": require("../../assets/media/Hanh dong/Chuyện Ngày Xưa ở Hollywood/Chuyen_Ngay_Xua_o_Hollywood.mp4"),
    "media/Hanh dong/Cuồng Nộ/Cuong_No.mp4": require("../../assets/media/Hanh dong/Cuồng Nộ/Cuong_No.mp4"),
    "media/Hanh dong/Cuộc Chiến Sân Cỏ/Cuoc_Chien_San_Co.mp4": require("../../assets/media/Hanh dong/Cuộc Chiến Sân Cỏ/Cuoc_Chien_San_Co.mp4"),
    "media/Hanh dong/Hành Tinh Cát 2/Hanh_Tinh_Cat_2.mp4": require("../../assets/media/Hanh dong/Hành Tinh Cát 2/Hanh_Tinh_Cat_2.mp4"),
    "media/Hanh dong/Sàn Đấu Sinh Tử/San_Dau_Sinh_Tu.mp4": require("../../assets/media/Hanh dong/Sàn Đấu Sinh Tử/San_Dau_Sinh_Tu.mp4"),
    "media/Hanh dong/Sát Thủ Đối Đầu/Sat_Thu_Doi_Dau.mp4": require("../../assets/media/Hanh dong/Sát Thủ Đối Đầu/Sat_Thu_Doi_Dau.mp4"),
    "media/Hanh dong/Thành Phố Quỷ/Thanh_Pho_Quy.mp4": require("../../assets/media/Hanh dong/Thành Phố Quỷ/Thanh_Pho_Quy.mp4"),
    "media/Hanh dong/Thế Chiến Z/The_Chien_Z.mp4": require("../../assets/media/Hanh dong/Thế Chiến Z/The_Chien_Z.mp4"),
    "media/Hanh dong/Venom Kèo Cuối/Venom_Keo_Cuoi.mp4": require("../../assets/media/Hanh dong/Venom Kèo Cuối/Venom_Keo_Cuoi.mp4"),
    "media/Hoat hinh/Cô Bé Người Cá Ponyo/Co_Be_Nguoi_Ca_Ponyo.mp4": require("../../assets/media/Hoat hinh/Cô Bé Người Cá Ponyo/Co_Be_Nguoi_Ca_Ponyo.mp4"),
    "media/Hoat hinh/Flow/Flow.mp4": require("../../assets/media/Hoat hinh/Flow/Flow.mp4"),
    "media/Hoat hinh/Kẻ Trộm Mặt Trăng 4/Ke_Trom_Mat_Trang_4.mp4": require("../../assets/media/Hoat hinh/Kẻ Trộm Mặt Trăng 4/Ke_Trom_Mat_Trang_4.mp4"),
    "media/Hoat hinh/Lâu Đài Di Động Của Pháp Sư Howl/Lau_Dai_Di_Dong_Cua_Phap_Su_Howl.mp4": require("../../assets/media/Hoat hinh/Lâu Đài Di Động Của Pháp Sư Howl/Lau_Dai_Di_Dong_Cua_Phap_Su_Howl.mp4"),
    "media/Hoat hinh/Na Tra Ma Đồng Giáng Thế/Na_Tra_Ma_Dong_Giang_The.mp4": require("../../assets/media/Hoat hinh/Na Tra Ma Đồng Giáng Thế/Na_Tra_Ma_Dong_Giang_The.mp4"),
    "media/Hoat hinh/Những Mảnh Ghép Cảm Xúc 2/Nhung_Manh_Ghep_Cam_Xuc_2.mp4": require("../../assets/media/Hoat hinh/Những Mảnh Ghép Cảm Xúc 2/Nhung_Manh_Ghep_Cam_Xuc_2.mp4"),
    "media/Hoat hinh/Shin Movie 32 Cậu Bé Bút Chì/Shin_Movie_32_Cau_Be_But_Chi.mp4": require("../../assets/media/Hoat hinh/Shin Movie 32 Cậu Bé Bút Chì/Shin_Movie_32_Cau_Be_But_Chi.mp4"),
    "media/Hoat hinh/Vùng Đất Linh Hồn/Vung_Dat_Linh_Hon.mp4": require("../../assets/media/Hoat hinh/Vùng Đất Linh Hồn/Vung_Dat_Linh_Hon.mp4"),
    "media/Moi phat hanh/Bậc Thầy Đàm Phán/Bac_Thay_Dam_Phan.mp4": require("../../assets/media/Moi phat hanh/Bậc Thầy Đàm Phán/Bac_Thay_Dam_Phan.mp4"),
    "media/Moi phat hanh/Chuyện Đời Bác Sĩ Nội Trú/Chuyen_Doi_Bac_Si_Noi_Tru.mp4": require("../../assets/media/Moi phat hanh/Chuyện Đời Bác Sĩ Nội Trú/Chuyen_Doi_Bac_Si_Noi_Tru.mp4"),
    "media/Moi phat hanh/Cung Điện Ma Ám/Cung_Dien_Ma_Am.mp4": require("../../assets/media/Moi phat hanh/Cung Điện Ma Ám/Cung_Dien_Ma_Am.mp4"),
    "media/Moi phat hanh/Khi Cuộc Đời Cho Bạn Quả Quýt/Khi_Cuoc_Doi_Cho_Ban_Qua_Quyt.mp4": require("../../assets/media/Moi phat hanh/Khi Cuộc Đời Cho Bạn Quả Quýt/Khi_Cuoc_Doi_Cho_Ban_Qua_Quyt.mp4"),
    "media/Moi phat hanh/Khó Dỗ Dành/Kho_Do_Danh.mp4": require("../../assets/media/Moi phat hanh/Khó Dỗ Dành/Kho_Do_Danh.mp4"),
    "media/Moi phat hanh/Trái Tim Bị Chôn Vùi/Trai_Tim_Bi_Chon_Vui.mp4": require("../../assets/media/Moi phat hanh/Trái Tim Bị Chôn Vùi/Trai_Tim_Bi_Chon_Vui.mp4"),
    "media/Moi phat hanh/Vô Ưu Độ/Vo_Uu_Do.mp4": require("../../assets/media/Moi phat hanh/Vô Ưu Độ/Vo_Uu_Do.mp4"),
    "media/Moi phat hanh/Ăn Chạy Yêu/An_Chay_Yeu.mp4": require("../../assets/media/Moi phat hanh/Ăn Chạy Yêu/An_Chay_Yeu.mp4"),
    "media/Tinh cam/Anora Lọ Lem Thời Hiện Đại/Anora_Lo_Lem_Thoi_Hien_Dai.mp4": require("../../assets/media/Tinh cam/Anora Lọ Lem Thời Hiện Đại/Anora_Lo_Lem_Thoi_Hien_Dai.mp4"),
    "media/Tinh cam/Baby Girl/Baby_Girl.mp4": require("../../assets/media/Tinh cam/Baby Girl/Baby_Girl.mp4"),
    "media/Tinh cam/Con Nhà Siêu Giàu Châu Á/Con_Nha_Sieu_Giau_Chau_A.mp4": require("../../assets/media/Tinh cam/Con Nhà Siêu Giàu Châu Á/Con_Nha_Sieu_Giau_Chau_A.mp4"),
    "media/Tinh cam/Cô Hầu Gái/Co_Hau_Gai.mp4": require("../../assets/media/Tinh cam/Cô Hầu Gái/Co_Hau_Gai.mp4"),
    "media/Tinh cam/Gia Tài Của Ngoại/Gia_Tai_Cua_Ngoai.mp4": require("../../assets/media/Tinh cam/Gia Tài Của Ngoại/Gia_Tai_Cua_Ngoai.mp4"),
    "media/Tinh cam/Hạnh Phúc Mãi Về Sau/Hanh_Phuc_Mai_Ve_Sau.mp4": require("../../assets/media/Tinh cam/Hạnh Phúc Mãi Về Sau/Hanh_Phuc_Mai_Ve_Sau.mp4"),
    "media/Tinh cam/La La Land/La_La_Land.mp4": require("../../assets/media/Tinh cam/La La Land/La_La_Land.mp4"),
    "media/Tinh cam/Queer/Queer.mp4": require("../../assets/media/Tinh cam/Queer/Queer.mp4"),
    "media/Tinh cam/Titanic/Titanic.mp4": require("../../assets/media/Tinh cam/Titanic/Titanic.mp4"),
    "media/Tinh cam/Đã Đến Lúc/Da_Den_Luc.mp4": require("../../assets/media/Tinh cam/Đã Đến Lúc/Da_Den_Luc.mp4"),
    "media/Xu huong/11 Chiến Binh Cảm Tử/11_Chien_Binh_Cam_Tu.mp4": require("../../assets/media/Xu huong/11 Chiến Binh Cảm Tử/11_Chien_Binh_Cam_Tu.mp4"),
    "media/Xu huong/Attack on Titan/Attack_on_Titan.mp4": require("../../assets/media/Xu huong/Attack on Titan/Attack_on_Titan.mp4"),
    "media/Xu huong/Cuộc Diễu Hành/Cuoc_Dieu_Hanh.mp4": require("../../assets/media/Xu huong/Cuộc Diễu Hành/Cuoc_Dieu_Hanh.mp4"),
    "media/Xu huong/Eephus/Eephus.mp4": require("../../assets/media/Xu huong/Eephus/Eephus.mp4"),
    "media/Xu huong/Faceless/Faceless.mp4": require("../../assets/media/Xu huong/Faceless/Faceless.mp4"),
    "media/Xu huong/Học Viện Siêu Anh Hùng/Hoc_Vien_Sieu_Anh_Hung.mp4": require("../../assets/media/Xu huong/Học Viện Siêu Anh Hùng/Hoc_Vien_Sieu_Anh_Hung.mp4"),
    "media/Xu huong/iHostage/iHostage.mp4": require("../../assets/media/Xu huong/iHostage/iHostage.mp4"),
    "media/Xu huong/Người Đàn Bà Ngoài Sân/Nguoi_Dan_Ba_Ngoai_San.mp4": require("../../assets/media/Xu huong/Người Đàn Bà Ngoài Sân/Nguoi_Dan_Ba_Ngoai_San.mp4"),
    "media/Xu huong/Thợ Săn Thành Phố/Tho_San_Thanh_Pho.mp4": require("../../assets/media/Xu huong/Thợ Săn Thành Phố/Tho_San_Thanh_Pho.mp4"),
    "media/Xu huong/Ánh Trăng Bên Cửa Sổ/Anh_Trang_Ben_Cua_So.mp4": require("../../assets/media/Xu huong/Ánh Trăng Bên Cửa Sổ/Anh_Trang_Ben_Cua_So.mp4"),
};
